// lib/data/exercises/chest_exercises.dart
import 'package:flutter/material.dart';
import '../widgets/exercise_widget.dart';

const List<ListItemData> chestExercises = [
  ListItemData(
    title: "Flat Bench Press",
    image: "assets/images/bench_press.jpg",
    colorCode: Colors.red,
    experienceLevel: "Advanced",
    muscleGroup: "Chest",
    subTitle: "Isolated lateral hypertrophy",
  ),
  ListItemData(
    title: "Incline Dumbbell Press",
    image: "assets/images/incline_press.jpg",
    colorCode: Colors.red,
    experienceLevel: "Advanced",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Cable Flyes",
    image: "assets/images/cable_fly.jpg",
    colorCode: Colors.blue,
    experienceLevel: "Beginner",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Push-ups",
    image: "assets/images/pushups.png",
    colorCode: Colors.green,
    experienceLevel: "Beginner",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Push-ups",
    image: "assets/images/pushups.png",
    colorCode: Colors.green,
    experienceLevel: "Beginner",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Push-ups",
    image: "assets/images/pushups.png",
    colorCode: Colors.green,
    experienceLevel: "Beginner",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Push-ups",
    image: "assets/images/pushups.png",
    colorCode: Colors.green,
    experienceLevel: "Beginner",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Push-ups",
    image: "assets/images/pushups.png",
    colorCode: Colors.green,
    experienceLevel: "Beginner",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Push-ups",
    image: "assets/images/pushups.png",
    colorCode: Colors.green,
    experienceLevel: "Beginner",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Push-ups",
    image: "assets/images/pushups.png",
    colorCode: Colors.green,
    experienceLevel: "Beginner",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Push-ups",
    image: "assets/images/pushups.png",
    colorCode: Colors.green,
    experienceLevel: "Beginner",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Push-ups",
    image: "assets/images/pushups.png",
    colorCode: Colors.green,
    experienceLevel: "Beginner",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Push-ups",
    image: "assets/images/pushups.png",
    colorCode: Colors.green,
    experienceLevel: "Beginner",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Push-ups",
    image: "assets/images/pushups.png",
    colorCode: Colors.green,
    experienceLevel: "Beginner",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Push-ups",
    image: "assets/images/pushups.png",
    colorCode: Colors.green,
    experienceLevel: "Beginner",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Push-ups",
    image: "assets/images/pushups.png",
    colorCode: Colors.green,
    experienceLevel: "Beginner",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Push-ups",
    image: "assets/images/pushups.png",
    colorCode: Colors.green,
    experienceLevel: "Beginner",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Push-ups",
    image: "assets/images/pushups.png",
    colorCode: Colors.green,
    experienceLevel: "Beginner",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Cable Flyes",
    image: "assets/images/cable_fly.jpg",
    colorCode: Colors.blue,
    experienceLevel: "Intermediate",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Cable Flyes",
    image: "assets/images/cable_fly.jpg",
    colorCode: Colors.blue,
    experienceLevel: "Intermediate",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Cable Flyes",
    image: "assets/images/cable_fly.jpg",
    colorCode: Colors.blue,
    experienceLevel: "Intermediate",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Cable Flyes",
    image: "assets/images/cable_fly.jpg",
    colorCode: Colors.blue,
    experienceLevel: "Intermediate",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Cable Flyes",
    image: "assets/images/cable_fly.jpg",
    colorCode: Colors.blue,
    muscleGroup: "Chest",
    experienceLevel: "Intermediate",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Cable Flyes",
    image: "assets/images/cable_fly.jpg",
    colorCode: Colors.blue,
    muscleGroup: "Chest",
    experienceLevel: "Intermediate",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Cable Flyes",
    image: "assets/images/cable_fly.jpg",
    colorCode: Colors.blue,
    experienceLevel: "Intermediate",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Cable Flyes",
    image: "assets/images/cable_fly.jpg",
    colorCode: Colors.blue,
    experienceLevel: "Intermediate",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Cable Flyes",
    image: "assets/images/cable_fly.jpg",
    colorCode: Colors.blue,
    experienceLevel: "Intermediate",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Cable Flyes",
    image: "assets/images/cable_fly.jpg",
    colorCode: Colors.blue,
    experienceLevel: "Intermediate",
    muscleGroup: "Chest",
    subTitle: "Complete shoulder hypertrophy",
  ),
];

const List<ListItemData> legsExercises = [
  ListItemData(
    title: "Barbell Squat",
    image: "assets/images/pushups.png",
    colorCode: Colors.red,
    experienceLevel: "Advanced",
    muscleGroup: "Legs",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Leg Press",
    image: "assets/images/pushups.png",
    colorCode: Colors.blue,
    experienceLevel: "Intermediate",
    muscleGroup: "Legs",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Leg Curls",
    image: "assets/images/pushups.png",
    colorCode: Colors.green,
    experienceLevel: "Beginner",
    muscleGroup: "Legs",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Romanian Deadlift",
    image: "assets/images/pushups.png",
    colorCode: Colors.red,
    experienceLevel: "Advanced",
    muscleGroup: "Legs",
    subTitle: "Complete shoulder hypertrophy",
  ),
];

const List<ListItemData> backExercises = [
  ListItemData(
    title: "Barbell Deadlift",
    image: "assets/images/pushups.png",
    colorCode: Colors.red,
    experienceLevel: "Advanced",
    muscleGroup: "Back",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Bent Over Rows",
    image: "assets/images/pushups.png",
    colorCode: Colors.blue,
    experienceLevel: "Intermediate",
    muscleGroup: "Back",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Pull-ups",
    image: "assets/images/pushups.png",
    colorCode: Colors.green,
    experienceLevel: "Beginner",
    muscleGroup: "Back",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Lat Pulldown",
    image: "assets/images/pushups.png",
    colorCode: Colors.blue,
    experienceLevel: "Beginner",
    muscleGroup: "Back",
    subTitle: "Complete shoulder hypertrophy",
  ),
];

const List<ListItemData> shouldersExercises = [
  ListItemData(
    title: "Overhead Press",
    image: "assets/images/pushups.png",
    colorCode: Colors.red,
    experienceLevel: "Advanced",
    muscleGroup: "Shoulders",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Lateral Raises",
    image: "assets/images/pushups.png",
    colorCode: Colors.blue,
    experienceLevel: "Intermediate",
    muscleGroup: "Shoulders",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Dumbbell Shoulder Press",
    image: "assets/images/pushups.png",
    colorCode: Colors.green,
    experienceLevel: "Beginner",
    muscleGroup: "Shoulders",
    subTitle: "Complete shoulder hypertrophy",
  ),
];

const List<ListItemData> armsExercises = [
  ListItemData(
    title: "Barbell Curls",
    image: "assets/images/pushups.png",
    colorCode: Colors.blue,
    experienceLevel: "Intermediate",
    muscleGroup: "Arms",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Tricep Dips",
    image: "assets/images/pushups.png",
    colorCode: Colors.red,
    experienceLevel: "Advanced",
    muscleGroup: "Arms",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Hammer Curls",
    image: "assets/images/pushups.png",
    colorCode: Colors.blue,
    experienceLevel: "Intermediate",
    muscleGroup: "Arms",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Skull Crushers",
    image: "assets/images/pushups.png",
    colorCode: Colors.red,
    experienceLevel: "Advanced",
    muscleGroup: "Arms",
    subTitle: "Complete shoulder hypertrophy",
  ),
];

const List<ListItemData> coreExercises = [
  ListItemData(
    title: "Plank",
    image: "assets/images/pushups.png",
    colorCode: Colors.green,
    experienceLevel: "Beginner",
    muscleGroup: "Core",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Crunches",
    image: "assets/images/pushups.png",
    colorCode: Colors.green,
    experienceLevel: "Beginner",
    muscleGroup: "Core",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Dead Bugs",
    image: "assets/images/pushups.png",
    colorCode: Colors.green,
    experienceLevel: "Beginner",
    muscleGroup: "Core",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Russian Twists",
    image: "assets/images/pushups.png",
    colorCode: Colors.green,
    experienceLevel: "Beginner",
    muscleGroup: "Core",
    subTitle: "Complete shoulder hypertrophy",
  ),
];

const List<ListItemData> cardioExercises = [
  ListItemData(
    title: "Running",
    image: "assets/images/pushups.png",
    colorCode: Colors.blue,
    experienceLevel: "Intermediate",
    muscleGroup: "Cardio",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Cycling",
    image: "assets/images/pushups.png",
    colorCode: Colors.blue,
    experienceLevel: "Intermediate",
    muscleGroup: "Cardio",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Jump Rope",
    image: "assets/images/pushups.png",
    colorCode: Colors.blue,
    experienceLevel: "Intermediate",
    muscleGroup: "Cardio",
    subTitle: "Complete shoulder hypertrophy",
  ),
  ListItemData(
    title: "Burpees",
    image: "assets/images/pushups.png",
    colorCode: Colors.blue,
    experienceLevel: "Intermediate",
    muscleGroup: "Cardio",
    subTitle: "Complete shoulder hypertrophy",
  ),
];

const List<Map<String, dynamic>> experienceLevel = [
  {"name": "Beginner", "color": Colors.green},
  {"name": "Intermediate", "color": Colors.blue},
  {"name": "Advanced", "color": Colors.red},
];
